apiVersion: apps/v1
kind: Deployment
metadata:
  name:   cpu-server
  namespace: default
  labels:
    app:   cpu-server
spec:
  selector:
    matchLabels:
      app:   cpu-server
  replicas: 2
  template:
    metadata:
      labels:
        app:   cpu-server
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:   cpu-server
        image:  vanguo996/demo-repo:v1
        ports:
        - containerPort:  39002
          name:   cpu-server

